---
- name: Deploy Microservices Containers
  hosts: web_servers
  become: yes

  vars:
    dockerhub_user: "aguenta"
    app_network: "cloud-final-network"

  tasks:
    - name: Ensure Docker is installed
      shell: |
        if command -v dnf >/dev/null 2>&1; then
          dnf install -y docker
        else
          yum install -y docker
        fi

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker network
      shell: docker network create {{ app_network }} || true

    - name: Pull user-service image
      shell: docker pull {{ dockerhub_user }}/user-service:latest

    - name: Pull product-service image
      shell: docker pull {{ dockerhub_user }}/product-service:latest

    - name: Pull order-service image
      shell: docker pull {{ dockerhub_user }}/order-service:latest

    - name: Pull api-gateway image
      shell: docker pull {{ dockerhub_user }}/api-gateway:latest

    - name: Remove old containers
      shell: |
        docker rm -f user-service product-service order-service api-gateway 2>/dev/null || true

    - name: Run user-service
      shell: |
        docker run -d \
          --name user-service \
          --restart unless-stopped \
          --network {{ app_network }} \
          -p 8081:8081 \
          {{ dockerhub_user }}/user-service:latest

    - name: Run product-service
      shell: |
        docker run -d \
          --name product-service \
          --restart unless-stopped \
          --network {{ app_network }} \
          -p 8082:8082 \
          -e CLOUD_SQS_PRODUCT_EVENTS_ENABLED=true \
          -e CLOUD_SQS_PRODUCT_EVENTS_QUEUE_URL="{{ sqs_queue_url | default('') }}" \
          {{ dockerhub_user }}/product-service:latest

    - name: Run order-service
      shell: |
        docker run -d \
          --name order-service \
          --restart unless-stopped \
          --network {{ app_network }} \
          -p 8083:8083 \
          -e SERVICES_USER_URL=http://user-service:8081 \
          -e SERVICES_PRODUCT_URL=http://product-service:8082 \
          -e CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_ENABLED=true \
          -e CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_QUEUE_URL="{{ sqs_queue_url | default('') }}" \
          {{ dockerhub_user }}/order-service:latest

    - name: Run api-gateway
      shell: |
        docker run -d \
          --name api-gateway \
          --restart unless-stopped \
          --network {{ app_network }} \
          -p 8080:8080 \
          -e SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://user-service:8081 \
          -e SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://product-service:8082 \
          -e SPRING_CLOUD_GATEWAY_ROUTES_2_URI=http://order-service:8083 \
          {{ dockerhub_user }}/api-gateway:latest

    - name: Show running containers
      shell: docker ps
      register: docker_ps

    - name: Print containers
      debug:
        var: docker_ps.stdout_lines
